# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f6b37a136f27f7d0aa9470aa33e7294b2be16dd55a88eeb9c8c37f5a1e1b65a41478c5b62ae447f1a60ca85d8b2cbde5971a113bdf83be4f6b7527d20161cc78

test:
  secret_key_base: f242b45b4af28dcb3dd0fb681a514f97cfa46b948381a100ae4135516926ed7cc443a0c981d1d76fe3debb1a59d212e21b668737cf3bab780502d40ca9cc8da3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
